server:
  port: 3434
  forward-headers-strategy: framework
spring:
  application:
    name: ShoppingCardDemo
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/shopping_card?useSSL=false
    password: postgres
    hikari:
      maximum-pool-size: 2
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        jdbc:
          lab:
            non_contexttual_creation: 'true'
    hibernate:
      ddl-auto: none